CasaDoCodigo/Models/Carrinho.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CasaDoCodigo.Models
{
    public class Carrinho
    {
        public ICollection<ItemCompra> ItensDeCompra { get; set; }
        public decimal ValorFrete { get; set; }
        public string CepDestino { get; set; }
        public Pagamento Pagamento { get; set; }

        public Carrinho()
        {
            this.ItensDeCompra = new SortedSet<ItemCompra>();
        }

        public List<ItemCompra> GetItensCompra()
        {
            return new List<ItemCompra>(this.ItensDeCompra);
        }

        public void AdicionarOuIncremantarQuantidadeDoItem(Livro livro, Formato formato)
        {
            ItemCompra item = new ItemCompra(livro, formato);

            if (JaExisteItem(item))
            {
                ItemCompra itemCarrinho = this.ProcurarItem(item);
                itemCarrinho.IncrementaQuantidade(item.Quantidade);
            }
            else
            {
                this.ItensDeCompra.Add(item);
            }

            CancelarPagamento();
        }

        public void RemoverItemPeloCodigoEFormato(string codigo, Formato formato)
        {
            ItemCompra itemARemover = ProcurarItemPeloId(codigo, formato);

            if (itemARemover != null)
            {
                this.ItensDeCompra.Remove(itemARemover);
            }

            if (!this.IsComLivrosImpressos())
            {
                this.ValorFrete = 0;
            }

            CancelarPagamento();
        }

        public Pagamento CriarPagamento(String numeroCartao, String nomeTitular)
        {
            Transacao transacao = new Transacao();
            transacao.Numero = numeroCartao;
            transacao.Titular = nomeTitular;
            transacao.Valor = this.GetTotal();

            //TODO: aqui, fazer a chamada pra um client REST...mas como eu ainda não cheguei 
            //em rest, vou deixar comentado pra ver o que fazer depois
            //this.Pagamento = this.clienteRest.criarPagamento(transacao);

            return this.Pagamento;
        }

        public Pedido FinalizarPedido()
        {
            Pedido pedido = new Pedido();
		    pedido.Data = DateTime.Now;
		    pedido.Itens = new SortedSet<ItemCompra>(this.ItensDeCompra);

            //TODO: possível chamada pra um client REST que ainda não saiu, deixando comentado
		    //this.pagamento = this.clienteRest.confirmarPagamento(pagamento);
		    
            
            pedido.Pagamento = this.Pagamento;

            //TODO: chamada pro JMS que ainda não sei o que é, mas provavelmente vou implementar um aqui
            //this.enviador.enviar(pedido);

		    this.LimparCarrinho();

		    return pedido;
        }

        public void AtualizarFrete(string novoCepDestino)
        {
            this.CepDestino = novoCepDestino;

            //TODO: criar a classe pra consumir o serviço dos Correios
            //ConsumidorServicoCorreios consumidorServicoCorreios = new ConsumidorServicoCorreios();
            //this.valorFrete = consumidorServicoCorreios.calculaFrete(novoCepDestino);
        }


        public decimal GetTotal()
        {
            decimal total = 0;

            foreach (ItemCompra item in this.ItensDeCompra)
            {
                total += item.GetTotal();
            }

            return total + this.ValorFrete;
        }

        public bool IsFreteCalculado()
        {
            return !this.ValorFrete.Equals(0) || !this.IsComLivrosImpressos();
        }

        public bool IsComLivrosImpressos()
        {
            foreach (ItemCompra itemCompra in this.ItensDeCompra) 
            {
			    if (itemCompra.isImpresso()) 
                {
				    return true;
			    }

		    }
		    return false;
        }

        public bool IsPagamentoCriado()
        {
            if(this.Pagamento == null)
            {
                return false;
            }
            return this.Pagamento.EhCriado();
        }

        public bool IsProntoPraSerFinalizado()
        {
            return this.IsFreteCalculado() && this.IsPagamentoCriado();
        }


        

        

        private void LimparCarrinho()
        {
            this.ItensDeCompra = null;
            this.ValorFrete = 0;
        }

   

        private ItemCompra ProcurarItem(ItemCompra itemProcurado)
        {
            foreach (ItemCompra item in this.ItensDeCompra)
            {
                if(item.Equals(itemProcurado))
                {
                    return item;
                }
            }

            throw new InvalidOperationException("Item não encontrado"); 
        }

        private ItemCompra ProcurarItemPeloId(string codigo, Formato formato)
        {
            foreach (ItemCompra item in this.ItensDeCompra)
            {
                if(item.Livro.Codigo.Equals(codigo) && item.Formato.Equals(formato))
                {
                    return item;
                }
            }

            return null;
        }

        //TODO: adicionar chamada para cancelar pagamento na api rest provavelmente
        private void CancelarPagamento()
        {
            this.Pagamento = null;
        }

        private bool JaExisteItem(ItemCompra item)
        {
            return this.ItensDeCompra.Contains(item);
        }

        private List<string> GetCodigosDosItensImpressos()
        {
            List<string> codigos = new List<string>();

            foreach (ItemCompra item in this.ItensDeCompra)
            {
                if(item.isImpresso())
                {
                    codigos.Add(item.Livro.Codigo);
                }
            }

            return codigos;
        }

        public void VerificarDisponibilidadeDosItensComSoap() 
        {
            //TODO CAFUSO: Ver se tem como melhorar esse cara aqui
            //EstoqueWSClient estoqueWS = new EstoqueWSClient();
            //List<string> codigos = this.GetCodigosDosItensImpressos();

            //string[] arrayCodigos = new string[10];

            //for (int i = 0; i < codigos.Count; i++)
            //{
            //    arrayCodigos[i] = codigos[1];
            //}

            //ServicoEstoque.ItemEstoque[] itens = estoqueWS.GetQuantidade(arrayCodigos);

            //foreach (ServicoEstoque.ItemEstoque item in itens)
            //{
            //    AtualizarQuantidadeDisponivelDoItemCompra(item);
            //}

            EstoqueWSClient estoqueWS = new EstoqueWSClient();
            //List<string> codigos = this.GetCodigosDosItensImpressos();

            string[] arrayCodigos = new string[this.ItensDeCompra.Count];

            for(int i = 0; i < this.ItensDeCompra.Count; i++)
            {
                arrayCodigos[i] = (this.ItensDeCompra.ToArray())[i].Livro.Codigo;
            }

            //for (int i = 0; i < codigos.Count; i++)
            //{
            //    arrayCodigos[i] = codigos[1];
            //}

            ServicoEstoque.ItemEstoque[] itens = estoqueWS.GetQuantidade(arrayCodigos);

            foreach (ServicoEstoque.ItemEstoque item in itens)
            {
                AtualizarQuantidadeDisponivelDoItemCompra(item);
            }
	    }

        private void AtualizarQuantidadeDisponivelDoItemCompra(ServicoEstoque.ItemEstoque itemEstoque)
        {
            //TODO CAFUSO: Ao testar, vamo ver se tatu do bem
            //

            ItemCompra item = this.ItensDeCompra.Where( i =>  i.TemCodigo(itemEstoque.Codigo  )).First(); //Iterables.find(this.itensDeCompra, new Predicate<ItemCompra>() {

           
            //@Override
            //public boolean apply(ItemCompra item) {
            //    return item.temCodigo(itemEstoque.getCodigo());
            //}

            item.QuantidadeEstoque = itemEstoque.Quantidade;
        }

    }
}

CasaDoCodigo/Models/ItemCompra.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CasaDoCodigo.Models
{
    public class ItemCompra
    {
        public virtual int Id { get; set; }
        public virtual Formato Formato { get; set; }
        public virtual int Quantidade { get; set; }
        public virtual int QuantidadeEstoque { get; set; }
        public virtual Livro Livro { get; set; }

        public ItemCompra()
        {

        }

        public ItemCompra(Livro livro, Formato formato)
        {
            this.Livro = livro;
            this.Formato = formato;
            this.Quantidade = 1;
            this.QuantidadeEstoque = 0;
        }

        public virtual void IncrementaQuantidade(int quantidade)
        {
            this.Quantidade += quantidade;
        }

        public virtual bool isImpresso()
        {
            return this.Formato.Equals(Formato.IMPRESSO);
        }

        public virtual string GetImagem()
        {
            return this.Livro.Imagem;
        }

        public virtual decimal GetValorUnico()
        {
            return this.Livro.GetValor(this.Formato);
        }

        public virtual decimal GetTotal()
        {
            decimal valorLivro = this.GetValorUnico();
            return valorLivro * this.Quantidade;
        }

        public virtual bool TemCodigo(string codigo)
        {
            return this.Livro.Codigo.Equals(codigo);
        }

	    public override string ToString() {
		    return "ItemCompra [titulo=" + this.Livro.Titulo + ", image=" + this.Livro.Imagem + ", codigo=" + this.Livro.Codigo
				    + ", formato=" + this.Formato + ", quantidade=" + this.Quantidade + ", quantidadeEstoque="
				    + this.QuantidadeEstoque + ", valorUnico=" + this.Livro.GetValor(this.Formato) + "]";
	    }

	    public override int GetHashCode() {
		    int prime = 31;
		    int result = 1;
		    result = prime * result + ((this.Livro.Codigo == null) ? 0 : this.Livro.Codigo.GetHashCode());
		    result = prime * result + ((this.Formato == null) ? 0 : this.Formato.GetHashCode());
		    return result;
	    }

	    public override bool Equals(Object obj) {
		    if (this == obj)
			    return true;
		    if (obj == null)
			    return false;
		    if (!(obj is ItemCompra))
			    return false;

		    ItemCompra other = (ItemCompra) obj;
		    if (this.Livro.Codigo == null) {
			    if (other.Livro.Codigo != null)
				    return false;
		    } else if (!this.Livro.Codigo.Equals(other.Livro.Codigo))
			    return false;
		    if (this.Formato != other.Formato)
			    return false;
		    return true;
	    }

    }
}

CasaDoCodigo/Controllers/CarrinhoController.cs
using CasaDoCodigo.DAO;
using CasaDoCodigo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CasaDoCodigo.Controllers
{
    public class CarrinhoController : Controller
    {
        private static Carrinho carrinho = new Carrinho();
        private LivroDAO dao;

        public CarrinhoController(LivroDAO dao)
        {
            //this.carrinho = carrinho;
            this.dao = dao;
        }

        // GET: Carrinho
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar()
        {
            carrinho.VerificarDisponibilidadeDosItensComSoap();

            return View(carrinho);
        }

        public ActionResult AdicionarItem(int id, Formato formato)
        {
            Livro livro = dao.BuscaPorId(id);
            carrinho.AdicionarOuIncremantarQuantidadeDoItem(livro, formato);
            return RedirectToAction("Listar");
        }

    }
}

CasaDoCodigo/Views/Carrinho/Listar.cshtml
@model CasaDoCodigo.Models.Carrinho

@{
    //ViewBag.Title = "Listar";
    Layout="~/Views/Shared/_Layout.cshtml"; 
}

<div class="container">

    <div class="row">
        <div class="col-md-9 col-xs-12">
            <h2>Seu carrinho de compras</h2>

            @*TODO: limpar o código comentado que deixei aqui*@

            @Html.ValidationMessage("messageInfo");
            @*<c:if test="${not empty messageInfo}">
                <div class="alert alert-info">${messageInfo}</div>
            </c:if>*@

            @Html.ValidationMessage("messageWarn");
            @*<c:if test="${not empty messageWarn}">
                <div class="alert alert-danger">${messageWarn}</div>
            </c:if>*@

            @if (Model.ItensDeCompra == null)
            {
                <div class="alert alert-info">
                    Nenhum livro no carrinho de
                    compras.
                </div>
                
                
                @Html.Partial("_CompreMais")
            }

            @*<c:if test="${empty carrinho.itensCompra}">
                <div class="alert alert-info">
                    Nenhum livro no carrinho de
                    compras.
                </div>

                <c:import url="/WEB-INF/views/compreMais.jsp" />

            </c:if>*@

            @*<c:if test="${not empty carrinho.itensCompra}">*@
            @if(Model.ItensDeCompra != null)
            { 
                <table id="cart-table" class="table table-hover">

                    <thead>
                        <tr>
                            <th width="65%" colspan="2">Livro</th>
                            <th width="10%">Preço</th>
                            <th width="5%">Qtd</th>
                            <th width="5%">Estoque</th>
                            <th width="10%">Total</th>
                            <th width="5%"></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach(var item in Model.ItensDeCompra)
                        { 
                        @*<c:foreach items="${carrinho.itensCompra}" var="item">*@
                            <tr>
                                <td>
                                    <img src="<c:url value=" />resources/imagens/small_@item.GetImagem()" />" />
                                </td>
                                <td>@item.Livro.Titulo (@item.Formato})</td>
                                <td class="numeric-cell">@item.GetValorUnico()</td>
                                <td class="numeric-cell">@item.Quantidade</td>
                                <td class="numeric-cell">
                                    @if (item.isImpresso()) { @item.QuantidadeEstoque }
                                    @*<c:if test="${item.impresso}">${item.quantidadeEstoque}</c:if>*@
                                </td>
                                <td class="numeric-cell">@item.GetTotal()</td>
                                <td>
                                    @*<a href="${linkCarrinhoRemover}?codigo=${item.codigo}&formato=${item.formato}"
                                       class="btn btn-default">
                                        <span class="glyphicon glyphicon-trash"></span> Excluir
                                    </a>*@
                                    @Html.ActionLink("Remover", "removerItem", "carrinho", 
                                                      new { codigo = item.Livro.Codigo, formato = item.Formato }, 
                                                        new { @class= "btn btn-default glyphicon glyphicon-trash" })
                                </td>
                            </tr>
                        }
                        @*</c:foreach>*@
                    </tbody>

                    <tfoot>
                        @if(Model.IsComLivrosImpressos())
                        { 
                        @*<c:if test="${carrinho.comLivrosImpressos}">*@
                            <tr>
                                <td></td>

                                <td colspan="6" align="right">
                                    @using (Html.BeginForm("CalcularCep", "Carrinho", FormMethod.Post))
                                    {
                                    @*<form action="${linkCarrinhoCalcularCep}" method="post">*@
                                        <span class="input-group">
                                            <span class="input-group-addon">CEP:</span> <input type="text"
                                                                                               class="form-control" value="@Model.CepDestino"
                                                                                               name="cepDestino" id="cepDestino" placeholder="Digite o cep">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit">
                                                    <span class="glyphicon glyphicon-usd"></span> Calcular
                                                    Frete
                                                </button>
                                            </span>
                                        </span>
                                    }
                                    @*</form>*@
                                </td>
                            </tr>
                            <tr>
                                <td colspan="4"></td>
                                <td colspan="3" align="right">
                                    <c:if test="${not empty carrinho.valorFrete}">Frete: ${carrinho.valorFrete}</c:if>
                                    @if (Model.ValorFrete != 0) 
                                    {
                                        @:Frete: @Model.ValorFrete 
                                    }
                                </td>
                            </tr>
                        }

                        <tr>
                            <td colspan="4">
                                @Html.Partial("_CompreMais")
                                @*<c:import url="/WEB-INF/views/compreMais.jsp" />*@
                            </td>

                            <td colspan="3" align="right">
                                <strong>
                                    Total:
                                    @*${carrinho.total}*@
                                    @Model.GetTotal()
                                </strong>
                            </td>
                        </tr>

                        @if(Model.IsPagamentoCriado())
                        {
                            
                        
                        @*<c:if test="${not carrinho.pagamentoCriado}">*@
                            <tr id="tr_form_cartao">
                                <td colspan="2"></td>
                                <td colspan="5" align="right">
                                    <div id="div_form_cartao" class="show">
                                        @using (Html.BeginForm("CriarPagamento", "Carrinho", FormMethod.Post))
                                        { 
                                        @*<form action="${linkCarrinhoCriarPagamento}" method="POST"
                                              role="form">*@
                                            <p class="lead text-success">Preencha os dados abaixo:</p>
                                            <div class="form-group">
                                                <label for="cartao">Número do cartão</label> <input type="text" class="form-control" name="numeroCartao"
                                                                                                    id="numeroCartao" placeholder="Digite o número do cartão"
                                                                                                    autocomplete="off">
                                            </div>
                                            <div class="form-group">
                                                <label for="nome">Nome do titular</label> <input type="text" class="form-control" name="titularCartao"
                                                                                                 id="titularCartao" placeholder="Digite o nome do titular"
                                                                                                 autocomplete="off">
                                            </div>
                                            <button type="submit" class="btn btn-success"
                                                    name="btn_pagamento" id="btn_pagamento">
                                                <span class="glyphicon glyphicon-credit-card"></span> Pagar
                                                com PayFast
                                            </button>
                                        }
                                        @*</form>*@
                                    </div>
                                </td>
                            </tr>
                        @*</c:if>*@
                        }

                        @if(Model.IsProntoPraSerFinalizado())
                        { 
                        @*<c:if test="${carrinho.prontoParaSerFinalizado}">*@
                            <tr>
                                <td></td>
                                <td colspan="6" align="right">
                                    <div id="divFinalizar">
                                        @using(Html.BeginForm("Finalizar", "Carrinho", FormMethod.Post))
                                        { 
                                        @*<form action="${linkCarrinhoFinalizar}" method="post">*@
                                            <button type="submit" class="btn btn-primary btn-lg"
                                                    name="btn_pagamento" id="btn_pagamento">
                                                <span class="glyphicon glyphicon-check"></span> Finalizar
                                                pedido
                                            </button>
                                        }
                                        @*</form>*@
                                    </div>
                                </td>
                            </tr>
                        }
                        @*</c:if>*@
                    </tfoot>
                </table>
            @*</c:if>*@
            }
        </div>

        @*TODO: ver se não tem que importar nada aqui mesmo*@
        @*<div class="col-md-3 col-xs-12">
            <c:import url="/WEB-INF/views/menu-treinamentos.jsp" />
        </div>*@
    </div>

    @*TODO: ver se não tem que importar nada aqui mesmo*@
    @*<c:import url="/WEB-INF/views/footer.jsp" />*@

</div>