CasaDoCodigo/Controllers/LojaController.cs
using CasaDoCodigo.DAO;
using CasaDoCodigo.Infra;
using CasaDoCodigo.Models;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CasaDoCodigo.Controllers
{
    public class LojaController : Controller
    {
        // GET: Loja
        public ActionResult Index()
        {
            IList<Livro> livros = new LivroDAO().Lista();
            return View(livros);
        }

        public ActionResult Livro(int id)
        {
            Livro livro = new LivroDAO().BuscaPorId(id);
            return View(livro);
        }
    }
}

CasaDoCodigo/Views/Shared/_CompreMais.cshtml
<h2>_CompreMais</h2>

<div class="row">
    <div class="col-md-12 col-xs-12">
        @Html.ActionLink("Continue comprando", "index", "loja", null, new { @class = "btn btn-info btn-lg" })
        @*<a class="btn btn-info btn-lg" href="<c:url value=" />loja/index" />">
        <span class="glyphicon glyphicon-book"></span> Continue comprando
        </a>*@
    </div>
</div>

CasaDoCodigo/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>

@*TODO: por que o layout tá zuado na página inicial? por qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq*@
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Home", "Index", "Loja")</li>
                    <li><a href="http://caelum.com.br">Caelum</a></li>
                    <li><a href="http://alura.com.br">Alura</a></li>
                    <li><a href="http://casadocodigo.com.br">Casa do código</a></li>
                    <li>
                        <a href="/carrinho/listar" class="btn btn-default btn-xs">
                            <span class="glyphicon glyphicon-shopping-cart"></span> Carrinho
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">

        <div class="row row-offcanvas row-offcanvas-right">
            <div class="col-md-9 col-xs-12">

                @RenderBody()

            </div>

            <div class="col-md-3 col-xs-12">

                <div class="well sidebar-nav">
                    <ul class="nav">
                        <li>Formação Front-end</li>
                        <li><a href="http://www.caelum.com.br/curso-html-css-javascript/">Desenvolvimento Web com HTML, CSS e JavaScript</a></li>
                        <li><a href="http://www.caelum.com.br/curso-javascript-jquery/">Programação front-end com JavaScript e jQuery</a></li>
                        <li>Cursos Mobile</li>
                        <li><a href="http://www.caelum.com.br/curso-android/">Desenvolvimento móvel com Google Android</a></li>
                        <li><a href="http://www.caelum.com.br/curso-ios-iphone-ipad/">Desenvolvimento móvel com iOS</a></li>
                        <li>Formação Java Avançada</li>
                        <li><a href="http://www.caelum.com.br/curso-persistencia-java-jpa-hibernate/">Persistência com JPA, Hibernate e EJB lite</a></li>
                        <li><a href="http://www.caelum.com.br/curso-java-web-jsf-cdi/">Web rica com JSF 2, Primefaces 4 e CDI</a></li>
                    </ul>
                </div>

            </div>

        </div>

        <hr>
        <footer>
            <p>© Caelum - Ensino e Inovação</p>
        </footer>

    </div>

    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>